#!/bin/bash
# Prosty skrypt do automatyzacji przepytywania
#
# Copyright (C) 2007,2016 Tomasz Długosz <tomek3d@gmail.com>
#
# Distributed under the terms of the GNU General Public License v3

info() {
  cat << KONIEC
NAZWA
     przepytaj - przeprowadza sprawdzenie opanowania materiału na kolokwium ;)

SKŁADNIA
     przepytaj nazwa_pliku
     gdzie nazwa_pliku wskazuje plik z materiałem do opanowania

SKŁADNIA PLIKU Z MATERIAŁEM
     Linie zawierające znak # traktowane są jako komentarz.
     W pozostałych liniach należy umieścić odpowiadające sobie fragmenty
     materiału oddzielone znakiem średnika (;).
     Przykładowo początek pliku mógłby wyglądać tak:

     # To jest komentarz
     Azot;N
     rower;bicycle
     rok bitwy pod Grunwaldem;1410
     2+2*2;6
KONIEC
  exit 1
}

pytaj() {
  reset
  echo -e '\033[36mPlik z materiałem załadowany!\033[0m'
  echo
  ile_bledow=0
  ile_pytan=0
  staryifs=$IFS
  export IFS='
'
  for i in `cat "$1"`;do
    ile_pytan=$(($ile_pytan+1))
    echo -e 'Pytanie nr \033[33m'$ile_pytan'\033[0m'
    echo -n `echo $i | cut -d ";" -f 1`" : "
    read odpowiedz
    poprawnie=`echo $i | cut -d ";" -f 2`
    if [ "$odpowiedz" = "$poprawnie" ];then
      echo -e '\033[32mdobrze!\033[0m'
    else
      echo -e '\033[31mBŁĄD!\033[0m'
      echo -e 'Miało być \033[32m'$poprawnie'\033[0m, a nie \033[31m'$odpowiedz'\033[0m!'
      ile_bledow=$(($ile_bledow+1))
    fi
  done
  export IFS=$staryifs
  echo -e 'Na \033[33m'$ile_pytan'\033[0m pytań było \033[31m'$ile_bledow'\033[0m błędów!'
}

if [ $# = 1 ];then
  if [ -f "$1" ]; then
    temp_file=$(mktemp)
    grep -v '#' "$1" | shuf > $temp_file
    pytaj $temp_file
    rm $temp_file
  else
    echo "Nie ma takiego pliku!"
  fi
else
    info
fi
